# Generated by Django 5.2.4 on 2025-07-14 10:10

import sneakers.models
import sneakers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to=sneakers.models.Sneaker._generate_file_path, validators=[sneakers.validators.validate_filetype, sneakers.validators.validate_filesize]),
        ),
    ]
